### ISSUE TITLE
use for each loop. read the article

### ISSUE THREAD

**Issue by vatolinrp** [nexon543/Task_5_Web_application_with_pagination#10]
https://docs.oracle.com/javase/8/docs/technotes/guides/language/foreach.html

https://github.com/nexon543/Task_5_Web_application_with_pagination/blob/4a778d86f53ca48a86b1fcdb6a6291aef6cc65fc/src/main/java/by/tc/task5/dao/xml/PlanetsDOMBuilder.java#L41

**Comment by nexon543** [comment]
I read the article but I can't use it to do forEach loop with NodeList
