### ISSUE TITLE
you are using intellij idea, you can remove: .settings bin/ .classpath .project

### ISSUE THREAD

**Issue by vatolinrp** [nexon543/Task_5_Web_application_with_pagination#2]
https://github.com/nexon543/Task_5_Web_application_with_pagination/blob/3c3300edc10a3bd807774086647a07275651c228/.gitignore#L1

**Comment by nexon543** [comment]
I need to use Eclipse at home for Java EE

**Comment by vatolinrp** [comment]
maybe switch to intellij idea at home as well?

**Comment by nexon543** [comment]
yes I will

**Comment by nexon543** [comment]
cba5b6a019f1507ac7dd4c834bbec7158c8ac241
