### ISSUE TITLE
the parse method should take something and return something

### ISSUE THREAD

**Issue by vatolinrp** [nexon543/Task_5_Web_application_with_pagination#8]
https://github.com/nexon543/Task_5_Web_application_with_pagination/blob/4a778d86f53ca48a86b1fcdb6a6291aef6cc65fc/src/main/java/by/tc/task5/dao/XmlDAOImpl.java#L24

**Comment by nexon543** [comment]
e429211079af4f9a935566ed8c58eb5b1200a3eb
